=== Loweise/liga-mx-xsd-xml/dtd/resultados.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Elemento Raíz: partido -->
  <xs:element name="partido">
    <xs:complexType>
      <xs:sequence>
        <!-- Permite exactamente 2 elementos equipo (local y visitante) -->
        <xs:element name="equipo" minOccurs="2" maxOccurs="2">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="goles" type="xs:nonNegativeInteger" />
              <xs:element name="posesion" type="xs:nonNegativeInteger" />
              <xs:element name="tarjetas" type="xs:nonNegativeInteger" />
            </xs:sequence>
            
            <!-- Atributo nombre -->
            <xs:attribute name="nombre" type="xs:string" use="required" />
            
            <!-- Atributo estadia restringido solo a "local" o "visitante" -->
            <xs:attribute name="estadia" use="optional">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="local" />
                  <xs:enumeration value="visitante" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>

      <!-- Atributo id del partido (permite enteros positivos o texto) -->
      <xs:attribute name="id" type="xs:positiveInteger" use="required" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Loweise/liga-mx-xsd-xml/xml/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<partido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../dtd/resultados.xsd"
         id="1">

    <equipo estadia="local" nombre="Monterrey">
        <goles>1</goles>
        <posesion>50</posesion>
        <tarjetas>0</tarjetas>
    </equipo>

    <equipo estadia="visitante" nombre="Cruz Azul">
        <goles>0</goles>
        <posesion>50</posesion>
        <tarjetas>1</tarjetas> 
    </equipo>

</partido>

=== Loweise/liga-mx-xsd-xml/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<partido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../dtd/resultados.xsd"
         id="1">

    <equipo estadia="local" nombre="UNAM">
        <goles>2</goles>
        <posesion>54</posesion>
        <tarjetas>1</tarjetas>
    </equipo>

    <equipo estadia="visitante" nombre="San Luis">
        <goles>3</goles>
        <posesion>46</posesion>
        <tarjetas>2</tarjetas> 
    </equipo>

</partido>

<partido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../dtd/resultados.xsd"
         id="1">

    <equipo estadia="local" nombre="Leon">
        <goles>2</goles>
        <posesion>56</posesion>
        <tarjetas>2</tarjetas>
    </equipo>

    <equipo estadia="visitante" nombre="Juarez">
        <goles>1</goles>
        <posesion>44</posesion>
        <tarjetas>2</tarjetas> 
    </equipo>

</partido>

<partido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../dtd/resultados.xsd"
         id="1">

    <equipo estadia="local" nombre="Necaxa">
        <goles>2</goles>
        <posesion>53</posesion>
        <tarjetas>3</tarjetas>
    </equipo>

    <equipo estadia="visitante" nombre="America">
        <goles>4</goles>
        <posesion>47</posesion>
        <tarjetas>2</tarjetas> 
    </equipo>

</partido>
